import "server-only";

import { randomUUID } from "node:crypto";

import type { LeadPayload } from "./types";

/**
 * The one place a lead leaves this application.
 *
 * Everything else — the form, the route, validation — is delivery-agnostic.
 * Swapping Resend for a CRM means changing this file and nothing else.
 *
 * Sent over Resend's HTTP API rather than its SDK, so the project takes no
 * dependency for a single POST.
 *
 * Three things this deliberately does not do:
 *
 *  - It does not log the lead. The previous version wrote the whole payload to
 *    the server log on every submission, which put names, email addresses,
 *    phone numbers and free-text notes into an operational log that nobody had
 *    agreed to as a store of personal data. It logs a submission id and an
 *    outcome code instead.
 *  - It does not treat the log as a lead store. A log is not durable, is not
 *    searched by anyone answering enquiries, and is not a backup. If delivery
 *    fails, the lead is not recorded anywhere — which is exactly why the route
 *    reports failure rather than success.
 *  - It does not report success unless the provider accepted the message.
 */

export type SubmitOutcome =
  /** The provider accepted it. `id` is the provider's own message id if given. */
  | { status: "delivered"; submissionId: string; providerId?: string }
  /** Definitively not delivered — the provider refused, or is not configured. */
  | { status: "failed"; submissionId: string; code: FailureCode }
  /** We stopped waiting. Delivery may or may not have happened. */
  | { status: "timeout"; submissionId: string };

export type FailureCode = "not-configured" | "provider-rejected" | "network";

const RESEND_ENDPOINT = "https://api.resend.com/emails";

/** Resend's shared sender, usable without verifying a domain first. */
const DEFAULT_FROM = "MyFinanceOfficer <onboarding@resend.dev>";

/**
 * Bounded, so a hanging provider cannot hold a serverless invocation open until
 * the platform kills it — which produced no response at all and left the form
 * showing a generic failure with no idea why.
 */
const TIMEOUT_MS = 8_000;

function formatEmail(payload: LeadPayload, submissionId: string): string {
  const lines = [
    `How they are paid: ${payload.paidBy}`,
    `Where they are now: ${payload.stage}`,
    `What they need: ${payload.needs.join(", ")}`,
    payload.sourcePage ? `Started from: ${payload.sourcePage}` : "Started from: not recorded",
    "",
    `Name:  ${payload.name}`,
    `Email: ${payload.email}`,
    `Phone: ${payload.phone || "not given"}`,
    "",
    payload.note ? `Note:\n${payload.note}` : "No note.",
    "",
    `Submission: ${submissionId}`,
  ];

  return lines.join("\n");
}

/**
 * Deliver one lead.
 *
 * `submissionId` is generated by the caller and passed through on a retry, so
 * the same enquiry sent twice carries the same key. Resend supports an
 * `Idempotency-Key` request header for exactly this: a repeat within the
 * provider's retention window returns the original result instead of sending a
 * second message. Verified against Resend's current HTTP API documentation for
 * POST /emails. If the provider ever stops honouring it the worst case is a
 * duplicate email, not a lost or mis-delivered lead.
 */
export async function submitLead(
  payload: LeadPayload,
  submissionId: string = randomUUID(),
): Promise<SubmitOutcome> {
  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.LEAD_TO_EMAIL;
  const from = process.env.LEAD_FROM_EMAIL || DEFAULT_FROM;

  if (!apiKey || !to) {
    /* Names which variable is missing for the operator, never for the client:
       the route maps this to a stable public message. */
    console.error(
      `[lead] ${submissionId} not-configured missing=${!apiKey ? "RESEND_API_KEY " : ""}${!to ? "LEAD_TO_EMAIL" : ""}`.trim(),
    );
    return { status: "failed", submissionId, code: "not-configured" };
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    const response = await fetch(RESEND_ENDPOINT, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
        /* Same enquiry, same key: a retry cannot produce a second email. */
        "Idempotency-Key": submissionId,
      },
      body: JSON.stringify({
        from,
        to: [to],
        reply_to: payload.email,
        subject: `New enquiry — ${payload.name}`,
        text: formatEmail(payload, submissionId),
      }),
      signal: controller.signal,
    });

    if (!response.ok) {
      /* Status only. The provider's body can quote the payload back, which is
         how personal data ends up in logs by accident. */
      console.error(`[lead] ${submissionId} provider-rejected status=${response.status}`);
      return { status: "failed", submissionId, code: "provider-rejected" };
    }

    const body = (await response.json().catch(() => null)) as { id?: string } | null;
    console.info(`[lead] ${submissionId} delivered`);
    return { status: "delivered", submissionId, providerId: body?.id };
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") {
      /* We stopped waiting. The provider may still have sent it, so this is
         reported as uncertain rather than as a failure. */
      console.error(`[lead] ${submissionId} timeout after=${TIMEOUT_MS}ms`);
      return { status: "timeout", submissionId };
    }

    console.error(
      `[lead] ${submissionId} network error=${error instanceof Error ? error.name : "unknown"}`,
    );
    return { status: "failed", submissionId, code: "network" };
  } finally {
    clearTimeout(timer);
  }
}
